# [Required]
# Basic component information
repo: l2MpsLN
organization: slaclab
url: https://github.com/slaclab/l2MpsLN
description: This is the LCLS-II MPS Link Node.

# [Required]
# Continous integration
approvalRule: all
testingCriteria: all
issueTracker: github
jiraProjectKey: n/a

# [Required]
# Environments this app runs on
environments:
   - ROCKY9
   - RHEL7

# [Required]
# Type of deployment
# Types: [ioc, hla, tools, matlab, pydm]
deploymentType: ioc

# [Optional] 
# Build method for building the component
# Can be a simple command like 'make'
build: make
