# ===========================================
# Autogenerated from MPS configuration database
# ===========================================
epicsEnvSet("SLOT_ID", "4")
epicsEnvSet("MPS_CONFIG_VERSION","2024-06-27-a")
epicsEnvSet("L2MPS_PREFIX", "MPLN:FEEH:MP01:1")
epicsEnvSet("DIGAID","340")
epicsEnvSet("BAYS","0")
epicsEnvSet("LOCATION","FEEH")
epicsEnvSet("LOCATION_INDEX","MP01")
epicsEnvSet("TYPE","DN")
epicsEnvSet("MODE_INPV", "MPS:UNDH:1:FACMODE CPP MSI")
epicsEnvSet("SHM","shm-b34-sp08-1")
epicsEnvSet("CRATE","0")
