epicsEnvSet("LN","139")
epicsEnvSet("MPS_CONFIG_VERSION","2024-08-17-a")
epicsEnvSet("L2MPS_PREFIX","MPLN:UNDH:MP04:1")
epicsEnvSet("CRATE","0")
epicsEnvSet("SLOT_ID","4")
epicsEnvSet("LOCATION","UNDH")
epicsEnvSet("LOCATION_INDEX","MP04")
epicsEnvSet("SHM","shm-b34-sp08-1")
epicsEnvSet("DIGAID","294")
epicsEnvSet("APPID","295")
epicsEnvSet("BAYS","2")
epicsEnvSet("CH0_MPS","")
epicsEnvSet("CH0_L1BSA","")
epicsEnvSet("CH0_P","CBLM:UNDH:1375")
epicsEnvSet("CH0_R","LOSS")
epicsEnvSet("CH0_EGU","mV")
epicsEnvSet("CH0_MPS","")

