TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

EDL += mps_analog_amc.edl
EDL += mps_analog_core.edl
EDL += mps_blm.edl
EDL += mps_concentrator.edl
EDL += mps_debug.edl
EDL += mps_digital_msg.edl
EDL += mps_ln.edl
EDL += mps_node_salt.edl
EDL += saveLoadConfig.edl
EDL += thr_ch.edl
EDL += mps_mit_msg.edl
EDL += mps_rtm_dio.edl
EDL += start_edm_li00-mp01.sh

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

