# ===========================================
# Autogenerated from MPS configuration database
# ===========================================
epicsEnvSet("SLOT_ID", "5")
epicsEnvSet("MPS_CONFIG_VERSION","2024-06-27-a")
epicsEnvSet("L2MPS_PREFIX", "MPLN:SPH:MP06:5")
epicsEnvSet("APPID","210")
epicsEnvSet("BAYS","1")
epicsEnvSet("LOCATION","SPH")
epicsEnvSet("LOCATION_INDEX","MP07")
epicsEnvSet("TYPE","AN")
epicsEnvSet("MODE_INPV", "MPS:UNDH:1:FACMODE CPP MSI")
epicsEnvSet("SHM","shm-b34-sp08-1")
epicsEnvSet("CRATE","0")

# Analog channels that are connected to this link node

# Channel 0
epicsEnvSet("CH0_MPS","")
epicsEnvSet("CH0_L1BSA","")
epicsEnvSet("CH0_P","PBLM:BSY0:714:H")
epicsEnvSet("CH0_R","LOSS")
epicsEnvSet("CH0_EGU","mV")

# Channel 1
#epicsEnvSet("CH1_MPS","")
#epicsEnvSet("CH1_L1BSA","")
epicsEnvSet("CH1_P","PBLM:BSY0:960:H")
#epicsEnvSet("CH1_R","LOSS")
#epicsEnvSet("CH1_EGU","mV")

# Channel 2
epicsEnvSet("CH2_MPS","")
epicsEnvSet("CH2_L1BSA","")
epicsEnvSet("CH2_P","LBLM:SPS:443:A")
epicsEnvSet("CH2_R","LOSS")
epicsEnvSet("CH2_EGU","mV")

# Channel 3
epicsEnvSet("CH1_WF","")
#epicsEnvSet("CH1_P","MPLN:GUNB:MP01:1")
epicsEnvSet("CH1_GCH","0")
