#!/bin/bash
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-sph-sp06-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-bsyh-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-bsyh-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-sps-sp05-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-sps-sp05-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-bsys-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-bsys-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltuh-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltuh-sp01-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltuh-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltuh-sp02-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltuh-sp03-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltus-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltus-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltus-sp02-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltus-sp03-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-ltus-sp04-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp01-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp01-3
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp02-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp03-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-undh-sp03-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-unds-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-unds-sp02-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-unds-sp02-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-unds-sp03-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-unds-sp03-2
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-feeh-sp01-1
/usr/local/lcls/epics/iocTop/l2MpsLN/current/scripts/setupBPClock.sh shm-fees-sp01-1
