bsasAssociateBsaChannels("bsaPort")
bsasBaseName("C0_I0","${WF0}")
bsasBaseName("C1_I0","${WF1}")
bsasBaseName("C2_I0","${WF2}")
bsasBaseName("C3_I0","${WF3}")
bsasBaseName("C4_I0","${WF4}")
bsasBaseName("C5_I0","${WF5}")
bsasAsynDriverConfigure("bsasPort", "mmio/AmcCarrierCore/AmcCarrierBsa/Bsas","${L2MPS_PREFIX}:SC_HXR","${L2MPS_PREFIX}:SC_SXR","${L2MPS_PREFIX}:SC_BSYD","${L2MPS_PREFIX}:SC_DIAG0")
dbLoadRecords("db/bsasCtrl.db", "DEV=${TPR},PORT=bsasPort")
