bsasAssociateBsaChannels("bsaPort")
$(CH0_MPS=#)bsasBaseName("I0_B0_C0","${CH0_P}:I0_${CH0_R}")
$(CH1_MPS=#)bsasBaseName("I0_B0_C1","${CH1_P}:I0_${CH1_R}")
$(CH2_MPS=#)bsasBaseName("I0_B0_C2","${CH2_P}:I0_${CH2_R}")
$(CH3_MPS=#)bsasBaseName("I0_B1_C0","${CH3_P}:I0_${CH3_R}")
$(CH4_MPS=#)bsasBaseName("I0_B1_C1","${CH4_P}:I0_${CH4_R}")
$(CH5_MPS=#)bsasBaseName("I0_B1_C2","${CH5_P}:I0_${CH5_R}")
#$(CH0_MPS=#)bsasBaseName("I0_B0_C0F","${CH0_P}:I0_${CH0_R}_FLOAT")
#$(CH1_MPS=#)bsasBaseName("I0_B0_C1F","${CH1_P}:I0_${CH1_R}_FLOAT")
#$(CH2_MPS=#)bsasBaseName("I0_B0_C2F","${CH2_P}:I0_${CH2_R}_FLOAT")
#$(CH3_MPS=#)bsasBaseName("I0_B1_C0F","${CH3_P}:I0_${CH3_R}_FLOAT")
#$(CH4_MPS=#)bsasBaseName("I0_B1_C1F","${CH4_P}:I0_${CH4_R}_FLOAT")
#$(CH5_MPS=#)bsasBaseName("I0_B1_C2F","${CH5_P}:I0_${CH5_R}_FLOAT")
$(CH0_MPS=#)bsasBaseName("I1_B0_C0","${CH0_P}:I0_${CH0_R}")
$(CH1_MPS=#)bsasBaseName("I1_B0_C1","${CH1_P}:I0_${CH1_R}")
$(CH2_MPS=#)bsasBaseName("I1_B0_C2","${CH2_P}:I0_${CH2_R}")
$(CH3_MPS=#)bsasBaseName("I1_B1_C0","${CH3_P}:I0_${CH3_R}")
$(CH4_MPS=#)bsasBaseName("I1_B1_C1","${CH4_P}:I0_${CH4_R}")
$(CH5_MPS=#)bsasBaseName("I1_B1_C2","${CH5_P}:I0_${CH5_R}")
#$(CH0_MPS=#)bsasBaseName("I1_B0_C0F","${CH0_P}:I1_${CH0_R}_FLOAT")
#$(CH1_MPS=#)bsasBaseName("I1_B0_C1F","${CH1_P}:I1_${CH1_R}_FLOAT")
#$(CH2_MPS=#)bsasBaseName("I1_B0_C2F","${CH2_P}:I1_${CH2_R}_FLOAT")
#$(CH3_MPS=#)bsasBaseName("I1_B1_C0F","${CH3_P}:I1_${CH3_R}_FLOAT")
#$(CH4_MPS=#)bsasBaseName("I1_B1_C1F","${CH4_P}:I1_${CH4_R}_FLOAT")
#$(CH5_MPS=#)bsasBaseName("I1_B1_C2F","${CH5_P}:I1_${CH5_R}_FLOAT")
bsasAsynDriverConfigure("bsasPort", "mmio/AmcCarrierCore/AmcCarrierBsa/Bsas","${BSAS}:SC_DIAG0","${BSAS}:SC_BSYD","${BSAS}:SC_HXR","${BSAS}:SC_SXR")
dbLoadRecords("db/bsasCtrl.db", "AREA=${LOCATION},IOC_UNIT=${LOCATION_INDEX},IOC_INST=${INST},PORT=bsasPort")
