bsaAdd("C0_I0",       "int32")
bsaAdd("C1_I0",       "int32")
bsaAdd("C2_I0",       "int32")
bsaAdd("C3_I0",       "int32")
bsaAdd("C4_I0",       "int32")
bsaAdd("C5_I0",       "int32")

bsaAsynDriverConfigure("bsaPort", "mmio/AmcCarrierCore/AmcCarrierBsa","strm/AmcCarrierDRAM/dram")
bsaList()
bsssAssociateBsaChannels("bsaPort")
bsssAsynDriverConfigure("bsssPort", "mmio/AmcCarrierCore/AmcCarrierBsa/Bsss")
dbLoadRecords("db/bsssCtrl.db", "DEV=${TPR},PORT=bsssPort")
