bsasAssociateBsaChannels("bsaPort")
bsasBaseName("C0_I0","${WF0}")
bsasBaseName("C1_I0","${WF1}")
bsasBaseName("C2_I0","${WF2}")
bsasBaseName("C3_I0","${WF3}")
bsasBaseName("C4_I0","${WF4}")
bsasBaseName("C5_I0","${WF5}")
bsasAsynDriverConfigure("bsasPort", "mmio/AmcCarrierCore/AmcCarrierBsa/Bsas","${BSAS}:SC_DIAG0","${BSAS}:SC_BSYD","${BSAS}:SC_HXR","${BSAS}:SC_SXR")
dbLoadRecords("db/bsasCtrl.db", "AREA=${LOCATION},IOC_UNIT=${LOCATION_INDEX},IOC_INST=${INST},PORT=bsasPort")
